openapi: 3.0.0
info:
  title: MLB EV Props API
  version: 1.0.0
servers:
  - url: http://localhost:5000
paths:
  /mlb_ev_props:
    get:
      summary: Get +EV MLB props
      parameters:
        - name: true_book
          in: query
          required: true
          schema:
            type: string
        - name: user_book
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: EV bets data
